/* data.js - 게임 데이터 (전역 상수) */

const CLASSES = {
  "전사": { hp: 120, attack: 15, defense: 8, desc: "높은 HP와 방어력을 가진 근접 전투 특화" },
  "마법사": { hp: 70, attack: 25, defense: 3, desc: "낮은 HP지만 강력한 마법 공격" },
  "도적": { hp: 90, attack: 18, defense: 5, desc: "균형 잡힌 스탯과 높은 치명타 확률" },
};

const ENEMY_TABLE = {
  goblin: { name: "고블린", hp: 30, atk: 8, def: 1, exp: 20, gold: 10 },
  wolf: { name: "늑대", hp: 45, atk: 12, def: 2, exp: 30, gold: 5 },
  orc: { name: "오크", hp: 70, atk: 16, def: 4, exp: 50, gold: 20 },
  troll: { name: "트롤", hp: 100, atk: 20, def: 6, exp: 80, gold: 35 },
  dragon_whelp: { name: "새끼 드래곤", hp: 110, atk: 26, def: 8, exp: 90, gold: 40 },
  dragon: { name: "드래곤", hp: 200, atk: 35, def: 10, exp: 200, gold: 150 },
  skeleton: { name: "해골전사", hp: 55, atk: 13, def: 3, exp: 40, gold: 12 },
  dark_mage: { name: "암흑마법사", hp: 50, atk: 22, def: 1, exp: 55, gold: 25 },
  vampire: { name: "뱀파이어", hp: 80, atk: 18, def: 5, exp: 70, gold: 40 },
  bandit: { name: "산적두목", hp: 55, atk: 14, def: 3, exp: 35, gold: 20 },
  undead_knight: { name: "언데드기사", hp: 90, atk: 20, def: 8, exp: 75, gold: 30 },
  dark_general: { name: "암흑장군", hp: 150, atk: 28, def: 8, exp: 120, gold: 80 },
  dwarf_golem: { name: "드워프 골렘", hp: 130, atk: 25, def: 12, exp: 95, gold: 50 },
  sand_scorpion: { name: "사막전갈", hp: 60, atk: 16, def: 5, exp: 45, gold: 15 },

  mummy: { name: "미라", hp: 85, atk: 19, def: 6, exp: 65, gold: 30 },
  pharaoh: { name: "파라오수호자", hp: 160, atk: 30, def: 9, exp: 130, gold: 90 },
  ice_golem: { name: "얼음골렘", hp: 110, atk: 22, def: 10, exp: 85, gold: 35 },
  frost_wyrm: { name: "서리비룡", hp: 180, atk: 32, def: 8, exp: 150, gold: 100 },
  swamp_snake: { name: "독사", hp: 40, atk: 14, def: 2, exp: 30, gold: 8 },
  swamp_witch: { name: "늪지마녀", hp: 70, atk: 24, def: 3, exp: 60, gold: 35 },
  sea_raider: { name: "해적", hp: 65, atk: 15, def: 4, exp: 40, gold: 25 },
  elf_guardian: { name: "엘프수호자", hp: 50, atk: 14, def: 4, exp: 38, gold: 15 },
  lake_spirit: { name: "호수정령", hp: 35, atk: 10, def: 2, exp: 25, gold: 20 },
  corrupted_spirit: { name: "타락한 정령", hp: 80, atk: 22, def: 4, exp: 65, gold: 20 },
  spirit_king: { name: "타락한 정령왕", hp: 170, atk: 32, def: 12, exp: 160, gold: 100 },
  labyrinth_guardian: { name: "미궁수호자", hp: 85, atk: 20, def: 7, exp: 70, gold: 30 },
  labyrinth_golem: { name: "미궁골렘", hp: 130, atk: 26, def: 11, exp: 100, gold: 50 },
  mercenary_duelist: { name: "용병결투사", hp: 75, atk: 18, def: 5, exp: 55, gold: 25 },
  fire_elemental: { name: "화염정령", hp: 95, atk: 24, def: 5, exp: 75, gold: 35 },
  lava_drake: { name: "용암드레이크", hp: 140, atk: 28, def: 7, exp: 110, gold: 60 },
  shadow_knight: { name: "그림자기사", hp: 100, atk: 22, def: 9, exp: 85, gold: 40 },
  dark_sentinel: { name: "어둠의파수꾼", hp: 120, atk: 25, def: 9, exp: 90, gold: 45 },
  shadow_lazarus: { name: "그림자라자러스", hp: 190, atk: 34, def: 10, exp: 180, gold: 120 },
};

const DROP_TABLE = {
  goblin: [{ item: "소형 포션", chance: 0.3 }],
  wolf: [{ item: "소형 포션", chance: 0.2 }],
  orc: [{ item: "대형 포션", chance: 0.25 }, { item: "낡은 검", chance: 0.15 }],
  troll: [{ item: "대형 포션", chance: 0.4 }, { item: "가죽 갑옷", chance: 0.2 }],
  dragon_whelp: [{ item: "대형 포션", chance: 0.5 }, { item: "사슬 갑옷", chance: 0.15 }],
  dragon: [{ item: "용의 심장", chance: 1.0 }, { item: "대형 포션", chance: 0.8 }],
  skeleton: [{ item: "소형 포션", chance: 0.3 }],
  dark_mage: [{ item: "대형 포션", chance: 0.35 }, { item: "마법 지팡이", chance: 0.1 }],
  vampire: [{ item: "대형 포션", chance: 0.4 }, { item: "해독제", chance: 0.3 }],
  bandit: [{ item: "소형 포션", chance: 0.4 }, { item: "낡은 검", chance: 0.2 }],
  undead_knight: [{ item: "사슬 갑옷", chance: 0.2 }, { item: "대형 포션", chance: 0.3 }],
  dark_general: [{ item: "강철 검", chance: 0.5 }, { item: "대형 포션", chance: 0.7 }],
  dwarf_golem: [{ item: "대지의 룬소드", chance: 0.3 }, { item: "대형 포션", chance: 0.6 }],
  sand_scorpion: [{ item: "해독제", chance: 0.4 }, { item: "소형 포션", chance: 0.3 }],
  mummy: [{ item: "대형 포션", chance: 0.3 }, { item: "고대 부적", chance: 0.15 }],
  pharaoh: [{ item: "파라오의 검", chance: 0.5 }, { item: "대형 포션", chance: 0.7 }],
  ice_golem: [{ item: "대형 포션", chance: 0.35 }, { item: "사슬 갑옷", chance: 0.15 }],
  frost_wyrm: [{ item: "서리의 검", chance: 0.5 }, { item: "대형 포션", chance: 0.8 }],
  swamp_snake: [{ item: "해독제", chance: 0.5 }, { item: "소형 포션", chance: 0.2 }],
  swamp_witch: [{ item: "대형 포션", chance: 0.4 }, { item: "마법 지팡이", chance: 0.2 }],
  sea_raider: [{ item: "소형 포션", chance: 0.3 }, { item: "낡은 검", chance: 0.25 }],
  elf_guardian: [{ item: "소형 포션", chance: 0.3 }, { item: "엘프의 로브", chance: 0.1 }],
  lake_spirit: [{ item: "소형 포션", chance: 0.5 }],
  corrupted_spirit: [{ item: "대형 포션", chance: 0.5 }, { item: "마법 로브", chance: 0.2 }],
  spirit_king: [{ item: "세계수의 이슬", chance: 1.0 }, { item: "고급 포션", chance: 0.9 }],
  labyrinth_guardian: [{ item: "대형 포션", chance: 0.35 }, { item: "해독제", chance: 0.2 }],
  labyrinth_golem: [{ item: "대형 포션", chance: 0.6 }, { item: "사슬 갑옷", chance: 0.3 }],
  mercenary_duelist: [{ item: "소형 포션", chance: 0.4 }, { item: "해독제", chance: 0.2 }],
  fire_elemental: [{ item: "대형 포션", chance: 0.4 }, { item: "고급 포션", chance: 0.15 }],
  lava_drake: [{ item: "고급 포션", chance: 0.5 }, { item: "강철 검", chance: 0.3 }],
  shadow_knight: [{ item: "대형 포션", chance: 0.4 }, { item: "사슬 갑옷", chance: 0.2 }],
  dark_sentinel: [{ item: "대형 포션", chance: 0.5 }, { item: "강철 검", chance: 0.25 }],
  shadow_lazarus: [{ item: "고급 포션", chance: 0.8 }, { item: "강화 갑옷", chance: 0.5 }],
};

const ITEMS = {
  "소형 포션": { type: "consumable", effect: "heal", value: 30, price: 20, desc: "HP를 30 회복한다" },
  "대형 포션": { type: "consumable", effect: "heal", value: 80, price: 50, desc: "HP를 80 회복한다" },
  "고급 포션": { type: "consumable", effect: "heal", value: 120, price: 100, desc: "HP를 120 회복한다" },
  "해독제": { type: "consumable", effect: "cure", value: 0, price: 30, desc: "독 상태를 해제한다" },
  "낡은 검": { type: "weapon", attack_bonus: 5, price: 40, desc: "공격력 +5" },
  "강철 검": { type: "weapon", attack_bonus: 12, price: 100, desc: "공격력 +12" },
  "마법 지팡이": { type: "weapon", attack_bonus: 18, price: 150, desc: "공격력 +18" },
  "도적의 단검": { type: "weapon", attack_bonus: 8, price: 80, desc: "공격력 +8" },
  "파라오의 검": { type: "weapon", attack_bonus: 25, price: 300, desc: "공격력 +25" },
  "서리의 검": { type: "weapon", attack_bonus: 22, price: 250, desc: "공격력 +22" },
  "봉인의 검": { type: "weapon", attack_bonus: 20, price: 0, desc: "공격력 +20, 라자러스에게 특효" },
  "용병의 도끼": { type: "weapon", attack_bonus: 15, price: 180, desc: "공격력 +15" },
  "엘프의 장궁": { type: "weapon", attack_bonus: 18, price: 220, desc: "공격력 +18, 숲의 기운이 깃든 정교한 활" },
  "대지의 룬소드": { type: "weapon", attack_bonus: 24, price: 200, desc: "공격력 +24, 드워프 장인의 걸작" },
  "염화의 검": { type: "weapon", attack_bonus: 30, price: 0, desc: "공격력 +30, 화산의 불꽃으로 단련된 전설의 검" },
  "드래곤 슬레이어": { type: "weapon", attack_bonus: 35, price: 0, desc: "공격력 +35, 용을 베어버리는 궁극의 대검" },
  "정령왕의 가지": { type: "weapon", attack_bonus: 28, price: 0, desc: "공격력 +28, 압도적인 마력을 품은 지팡이" },
  "가죽 갑옷": { type: "armor", defense_bonus: 4, price: 60, desc: "방어력 +4" },
  "사슬 갑옷": { type: "armor", defense_bonus: 9, price: 120, desc: "방어력 +9" },
  "마법 로브": { type: "armor", defense_bonus: 3, price: 90, desc: "방어력 +3" },
  "엘프의 로브": { type: "armor", defense_bonus: 6, price: 0, desc: "방어력 +6" },
  "강화 갑옷": { type: "armor", defense_bonus: 7, price: 140, desc: "방어력 +7" },
  "용암 갑옷": { type: "armor", defense_bonus: 12, price: 0, desc: "방어력 +12" },
  "행운의 부적": { type: "special", price: 0, desc: "도망 성공률 +20%" },
  "지도 조각": { type: "special", price: 0, desc: "어딘가의 지도 조각" },
  "고대 부적": { type: "special", price: 0, desc: "고대의 부적" },
  "달빛 장신구": { type: "special", price: 0, desc: "달빛이 깃든 장신구" },
  "봉인 반지": { type: "special", price: 0, desc: "왕의 봉인 반지. 모든 것의 시작이자 끝" },
  "용의 심장": { type: "special", price: 0, desc: "뜨겁게 고동치는 전설적인 드래곤의 심장" },
  "세계수의 잎사귀": { type: "consumable", effect: "heal", value: 150, price: 80, desc: "HP를 150 회복한다. 숲의 축복" },
  "세계수의 이슬": { type: "consumable", effect: "heal", value: 300, price: 500, desc: "HP를 300 회복한다. 정령의 축복" },
};

const SHOP_STOCK = ["소형 포션", "대형 포션", "해독제", "낡은 검", "강철 검", "가죽 갑옷", "사슬 갑옷"];
const MERC_SHOP_STOCK = ["소형 포션", "대형 포션", "고급 포션", "해독제", "용병의 도끼", "강화 갑옷"];

const AREAS = {
  town: { name: "아르카디아", unlock_condition: null, lock_hint: null, encounter_chance: 0, encounter_enemies: [], desc: "아르카디아 마을의 따뜻한 거리." },
  forest: { name: "어두운 숲", unlock_condition: null, lock_hint: null, encounter_chance: 0.35, encounter_enemies: ["goblin", "wolf"], desc: "어둠이 짙은 숲." },
  cave: { name: "몬스터 동굴", unlock_condition: { flag: "forest_cleared" }, lock_hint: "숲을 먼저 정리해야 합니다.", encounter_chance: 0.40, encounter_enemies: ["skeleton", "dark_mage"], desc: "음침한 동굴 입구." },
  dwarf_mine: { name: "드워프 광산", unlock_condition: { flag: "cave_cleared" }, lock_hint: "동굴을 먼저 탐색해야 광산으로 가는 길이 열립니다.", encounter_chance: 0.30, encounter_enemies: ["goblin", "dwarf_golem"], desc: "거대한 지하 광산. 곡괭이 소리가 울려퍼진다." },
  river: { name: "안개 강가", unlock_condition: { flag: "forest_cleared" }, lock_hint: "숲을 먼저 정리해야 합니다.", encounter_chance: 0.20, encounter_enemies: ["wolf", "bandit"], desc: "안개가 자욱한 강가." },
  ruins: { name: "저주받은 폐허", unlock_condition: { flag: "forest_cleared" }, lock_hint: "숲을 먼저 정리해야 합니다.", encounter_chance: 0.45, encounter_enemies: ["skeleton", "vampire"], desc: "무너진 폐허." },
  bandit_camp: { name: "산적 야영지", unlock_condition: { any_flag: ["cave_cleared", "river_cleared", "ruins_cleared"] }, lock_hint: "동굴/강가/폐허 중 한 곳을 먼저 해결하세요.", encounter_chance: 0.25, encounter_enemies: ["bandit", "orc"], desc: "산적들의 야영지." },
  castle_gate: { name: "마왕의 성 정문", unlock_condition: { flag: "bandit_camp_cleared" }, lock_hint: "산적 야영지를 먼저 해결하세요.", encounter_chance: 0.50, encounter_enemies: ["undead_knight"], desc: "거대한 검은 성벽." },
  castle_inside: { name: "성 내부", unlock_condition: { flag: "castle_gate_cleared" }, lock_hint: "성문을 먼저 돌파하세요.", encounter_chance: 0.30, encounter_enemies: ["undead_knight", "dark_mage"], desc: "차가운 성 복도." },
  throne: { name: "마왕의 방", unlock_condition: { flag: "castle_inside_cleared" }, lock_hint: "성 내부를 먼저 탐색하세요.", encounter_chance: 0, encounter_enemies: [], desc: "거대한 왕좌의 방." },
  harbor: { name: "포구 마을", unlock_condition: null, lock_hint: null, encounter_chance: 0, encounter_enemies: [], desc: "파도 소리와 갈매기 울음." },
  swamp: { name: "독안개 늪", unlock_condition: null, lock_hint: null, encounter_chance: 0.40, encounter_enemies: ["swamp_snake", "swamp_witch"], desc: "독안개가 피어오르는 늪지대." },
  desert_town: { name: "사하르 마을", unlock_condition: null, lock_hint: null, encounter_chance: 0, encounter_enemies: [], desc: "이국적인 향신료 냄새." },
  pyramid: { name: "파라오의 피라미드", unlock_condition: { flag: "desert_explored" }, lock_hint: "사하르 마을을 먼저 탐색하세요.", encounter_chance: 0.50, encounter_enemies: ["mummy", "skeleton"], desc: "거대한 피라미드." },
  oasis: { name: "오아시스", unlock_condition: null, lock_hint: null, encounter_chance: 0, encounter_enemies: [], desc: "사막의 오아시스." },
  ice_cave: { name: "빙하 동굴", unlock_condition: { flag: "castle_gate_cleared" }, lock_hint: "성 정문을 먼저 돌파하세요.", encounter_chance: 0.45, encounter_enemies: ["ice_golem", "frost_wyrm"], desc: "빙하 동굴." },
  elf_village: { name: "엘프 마을", unlock_condition: { flag: "forest_cleared" }, lock_hint: "숲을 먼저 정리해야 합니다.", encounter_chance: 0.15, encounter_enemies: ["elf_guardian"], desc: "고요한 엘프 숲." },
  spirit_forest: { name: "정령왕의 숲", unlock_condition: { flag: "elf_village_visited" }, lock_hint: "엘프 마을을 먼저 방문해야 비밀 통로가 열립니다.", encounter_chance: 0.35, encounter_enemies: ["corrupted_spirit", "wolf"], desc: "타락한 마력이 맴도는 울창한 숲." },
  moonlight_lake: { name: "달빛 호수", unlock_condition: null, lock_hint: null, encounter_chance: 0.10, encounter_enemies: ["lake_spirit"], desc: "달빛이 수면 위에 춤추는 호수." },
  labyrinth: { name: "지하 미궁", unlock_condition: { flag: "ruins_cleared" }, lock_hint: "폐허를 먼저 정리하세요.", encounter_chance: 0.45, encounter_enemies: ["labyrinth_guardian", "skeleton"], desc: "어둠 속 미궁 통로." },
  mercenary_camp: { name: "용병단 야영지", unlock_condition: { flag: "bandit_camp_cleared" }, lock_hint: "산적 야영지를 먼저 해결하세요.", encounter_chance: 0.10, encounter_enemies: ["mercenary_duelist"], desc: "용병들의 야영지." },
  dark_tower: { name: "어둠의 탑", unlock_condition: { flag: "castle_inside_cleared" }, lock_hint: "성 내부를 먼저 탐색하세요.", encounter_chance: 0.50, encounter_enemies: ["shadow_knight", "dark_sentinel"], desc: "검은 탑. 그림자가 일렁인다." },
  volcano: { name: "화산 지대", unlock_condition: { flag: "pyramid_cleared" }, lock_hint: "피라미드를 먼저 공략하세요.", encounter_chance: 0.40, encounter_enemies: ["fire_elemental", "lava_drake"], desc: "화산 열기가 대기를 달군다." },
  dragon_dungeon: { name: "드래곤의 던전", unlock_condition: { flag: "volcano_cleared" }, lock_hint: "화산 지대를 먼저 정복해야 합니다.", encounter_chance: 0.50, encounter_enemies: ["dragon_whelp", "lava_drake"], desc: "숨 쉬기조차 힘든 초고온의 거대한 둥지." },
};

// 타일 기반 이동용 추가 지역(이벤트는 없고 이동/조우용)
AREAS.desert = {
  name: "사하르 사막",
  unlock_condition: null,
  lock_hint: null,
  encounter_chance: 0.30,
  encounter_enemies: ["sand_scorpion", "bandit"],
  desc: "뜨거운 모래바람이 시야를 가린다.",
};
AREAS.ice = {
  name: "빙하 지대",
  unlock_condition: { flag: "castle_gate_cleared" },
  lock_hint: "마왕의 성 정문을 먼저 돌파하세요.",
  encounter_chance: 0.35,
  encounter_enemies: ["ice_golem", "undead_knight"],
  desc: "얼어붙은 빙하 지대. 발밑이 미끄럽다.",
};

const TERRAIN = {
  "#": { passable: false, zone: null },
  "w": { passable: false, zone: null },
  "^": { passable: false, zone: null },
  ".": { passable: true, zone: null },
  "=": { passable: true, zone: null },
  "f": { passable: true, zone: "forest" },
  "c": { passable: true, zone: "cave" },
  "q": { passable: true, zone: "dwarf_mine" },
  "r": { passable: true, zone: "river" },
  "u": { passable: true, zone: "ruins" },
  "b": { passable: true, zone: "bandit_camp" },
  "g": { passable: true, zone: "castle_gate" },
  "i": { passable: true, zone: "castle_inside" },
  "a": { passable: true, zone: "harbor" },
  "d": { passable: true, zone: "desert" },
  "n": { passable: true, zone: "swamp" },
  "x": { passable: true, zone: "ice" },
  "e": { passable: true, zone: "elf_village" },
  "s": { passable: true, zone: "spirit_forest" },
  "m": { passable: true, zone: "moonlight_lake" },
  "y": { passable: true, zone: "labyrinth" },
  "j": { passable: true, zone: "mercenary_camp" },
  "t": { passable: true, zone: "dark_tower" },
  "v": { passable: true, zone: "volcano" },
  "z": { passable: true, zone: "dragon_dungeon" },
};

const LOCATIONS = {
  T: { name: "아르카디아", zone: "town" },
  F: { name: "어두운 숲", zone: "forest" },
  C: { name: "몬스터 동굴", zone: "cave" },
  Q: { name: "드워프 광산", zone: "dwarf_mine" },
  R: { name: "안개 강가", zone: "river" },
  U: { name: "저주받은 폐허", zone: "ruins" },
  B: { name: "산적 야영지", zone: "bandit_camp" },
  G: { name: "마왕의 성 정문", zone: "castle_gate" },
  I: { name: "성 내부", zone: "castle_inside" },
  K: { name: "마왕의 방", zone: "throne" },
  H: { name: "포구 마을", zone: "harbor" },
  D: { name: "사하르 마을", zone: "desert_town" },
  P: { name: "파라오의 피라미드", zone: "pyramid" },
  O: { name: "오아시스", zone: "oasis" },
  W: { name: "독안개 늪", zone: "swamp" },
  L: { name: "빙하 동굴", zone: "ice_cave" },
  E: { name: "엘프 마을", zone: "elf_village" },
  S: { name: "정령왕의 숲", zone: "spirit_forest" },
  M: { name: "달빛 호수", zone: "moonlight_lake" },
  Y: { name: "지하 미궁", zone: "labyrinth" },
  J: { name: "용병단 야영지", zone: "mercenary_camp" },
  A: { name: "어둠의 탑", zone: "dark_tower" },
  V: { name: "화산 지대", zone: "volcano" },
  Z: { name: "드래곤의 던전", zone: "dragon_dungeon" },
};

const RAW_MAP = [
  "###########################################################################",
  "#.^^^^^^^.........................................................^^^^^^^^#",
  "#.^^^^^^^...................xxxxxxxxxxxxxxxxxxxx..................^^^^^^^^#",
  "#.^^^^^^^...................xxxxxxxxxLxxxxxxxxxx..................^^^^^^^^#",
  "#...........................xxxxxxxxx=xxxxxxxxxx..........................#",
  "#....................................=....................................#",
  "#....................................K.................ttttttttt..........#",
  "#....................................=.................ttttttttt..........#",
  "#.............................iiiiiii=iiiiiii..........ttttAtttt..........#",
  "#.............................iiiiiiiIiiiiii============tttttttt..........#",
  "#...eeeeeeeeeeeee.............iiiiiii=iiiiiii..........ttttttttt..........#",
  "#...eeeeeeeeeeeee....................=.................ttttttttt..........#",
  "#...eeeeeeeeeeeee.............ggggggg=ggggggg.............................#",
  "#...eeeeeeEeeeee===============ggggggGggggggg.............................#",
  "#...eeeeeeeeeeeee.............ggggggg=ggggggg.............................#",
  "#...eeee=eeeeeeee...............jjjjj=jjjjj...............................#",
  "#...ssss=ssssssss...............jjjjjJjjjjj...............................#",
  "#...ssssSssssssss...............jjjjj=jjjjj...............................#",
  "#...sssssssssssss.............bbbbbbb=bbbbbbb.............................#",
  "#..........qqqqqqq............bbbbbbbBbbbbbbb.............................#",
  "#..........qqqqQqq=...........bbbbbbb=bbbbbbb.............................#",
  "#.............cccc=ccccccccccc...rrrrrrr=rrrrrrr...uuuuuuuuuuuuu.............#",
  "#.............ccccccCcccccc...rrrrrrrRrrrrrrr...uuuuuuUuuuuuu.............#",
  "#.............cccccc=cccccc...rrrrrrr=rrrrrrr...uuuuuu=uuuuuu.............#",
  "#...................===========......=......===========...................#",
  "#.............................fffffff=fffffff.....yyyy=yyyy...............#",
  "#.............................fffffffFfffffff.....yyyyYyyyy...............#",
  "#..............mmmmmmmmm......fffffff=fffffff.....yyyyyyyyy...............#",
  "#......aaaHaa========================T========================D...........#",
  "#wwwwwwaaaaaaa.mmmmMmmm===============........................=...........#",
  "#wwwwwwaaaaaa=.mmmmmmmmm............................dddddddddd=dddddddd...#",
  "#wwwwww......=.mmmmmmmmm............................dddddddddd=dddddddd...#",
  "#wwwwww......=......................................dddddddddd=dddddddd...#",
  "#wwwwww.nnnnn=nnnnn.................................dddddddddd=dddddddd...#",
  "#wwwwww.nnnnnnnnnnn.................................dddddddddd=dddddddd...#",
  "#wwwwww.nnnnnWnnnnn.................................dddddddddd=dddddddd...#",
  "#wwwwww.nnnnnnnnnnn.................................ddddddddddPdddddddd...#",
  "#wwwwww.nnnnnnnnnnn.................................dddddddddd=dddddddd...#",
  "#wwwwww.............................................dddddddddd=dddddddd...#",
  "#wwwwww.............................................ddddddddddOdddddddd...#",
  "#wwwwww.............................................dddddddddd=dddddddd...#",
  "#wwwwww.............................................dddvvvvvvv=vvvvvvdd...#",
  "#...................................................dddvvvvvvv=vvvvvvdd...#",
  "#.^^^^^.............................................dddvvvvvvvVvvvvvvdd...#",
  "#.^^^^^.............................................dddvvvvvvv=vvvvvvdd...#",
  "#.^^^^^...zzzzzzzz...zzzzzz............................vvvvvv=vvvvvvv.....#",
  "#.^^^^^...zzzzZzzz=..zzzzzz............................vvvvvv=vvvvvvv.....#",
  "#.^^^^^...zzzzzzzz=zzzzzzzz............................======.............#",
  "###########################################################################",
];
